# Generated by Django 4.0 on 2022-01-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatar.svg', null=True, upload_to='images/'),
        ),
    ]
